# Generated by Django 4.2.24 on 2025-10-18 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Progresso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arvores', models.PositiveIntegerField(default=5, help_text='Quantidade atual de árvores.')),
                ('meta_arvores', models.PositiveIntegerField(default=10, help_text='Meta de árvores para vencer.')),
                ('acertos_consecutivos', models.PositiveIntegerField(default=0, help_text='Acertos consecutivos até plantar uma árvore.')),
                ('total_acertos', models.PositiveIntegerField(default=0)),
                ('total_erros', models.PositiveIntegerField(default=0)),
                ('fase_atual', models.PositiveIntegerField(default=1)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progresso', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
