# Generated by Django 4.2.24 on 2025-10-18 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Enunciado da Pergunta')),
                ('tipo', models.CharField(choices=[('VF', 'Verdadeiro ou Falso'), ('ME', 'Múltipla Escolha')], default='ME', max_length=2, verbose_name='Tipo de Pergunta')),
                ('correta', models.CharField(blank=True, max_length=255, null=True, verbose_name='Resposta Correta (para VF ou identificação interna)')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Alternativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('is_correta', models.BooleanField(default=False)),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternativas', to='pergunta.pergunta')),
            ],
        ),
    ]
